Fix problems importing xml
```
Servlet.service() for servlet [FF4jDispatcherServlet] in context with path [] threw exception
ognl.OgnlException: source is null for getProperty(null, "featureStore")
	at ognl.OgnlRuntime.getProperty(OgnlRuntime.java:2327)
	at ognl.ASTProperty.getValueBody(ASTProperty.java:114)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.Ognl.getValue(Ognl.java:494)
	at ognl.Ognl.getValue(Ognl.java:458)
	at org.thymeleaf.standard.expression.OgnlVariableExpressionEvaluator.evaluate(OgnlVariableExpressionEvaluator.java:114)
	... 124 common frames omitted
Wrapped by: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "homebean.featureStore" (home:40)
	at org.thymeleaf.standard.expression.OgnlVariableExpressionEvaluator.evaluate(OgnlVariableExpressionEvaluator.java:128)
```