Junit version change from 4.4 to 4.5
The JUnit test only works with 4.5 onwards, otherwise it will give a java.lang.NoClassDefFoundError: org/junit/runners/BlockJUnit4ClassRunner.